# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: required

before_install:
  - sudo apt-get install libgdal-dev libhdf5-dev libnetcdf-dev libxml2-dev cmake
  - git clone https://github.com/lutraconsulting/MDAL.git
  - cd MDAL
  - mkdir build;cd build
   ## DONE AS ROOT, BECAUSE otherwise fail for some reason
  - cmake -DCMAKE_BUILD_TYPE=Rel -DENABLE_TESTS=ON  ..
  - make
  - sudo make all install
  - sudo ldconfig

