// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rmdal0
NumericVector rmdal0();
RcppExport SEXP _rmdal0_rmdal0() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rmdal0());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rmdal_rmdal0();

static const R_CallMethodDef CallEntries[] = {
    {"_rmdal0_rmdal0", (DL_FUNC) &_rmdal0_rmdal0, 0},
    {"_rmdal_rmdal0", (DL_FUNC) &_rmdal_rmdal0, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmdal0(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
