# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmdal0 <- function() {
    .Call('_rmdal0_rmdal0', PACKAGE = 'rmdal0')
}

